import React from "react";
import "../globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const MarketingLayout = ({ children }: { children?: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <h1>Navbar header</h1>
        </nav>
        <h1>Marketing Layout</h1>
        {children}
        <footer>Main footer</footer>
      </body>
    </html>
  );
};

export default MarketingLayout;
