import NextTopLoader from "nextjs-toploader";
import "./globals.css";
import { Inter } from "next/font/google";
import PageTransition from "@/components/PageTransition";
import Header from "@/components/Header";
import CartContextProvider from "@/context/CartContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextTopLoader color="red" />
        <CartContextProvider>
          <main className="container mx-auto max-w-2xl mt-4 space-y-4 px-6">
            <Header />
            <PageTransition>{children}</PageTransition>
          </main>
        </CartContextProvider>
      </body>
    </html>
  );
}
